<?php
/**
 * AssetAddOrUpdateSubjectInfoBodyWrapperTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest API v1.2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AssetAddOrUpdateSubjectInfoBodyWrapperTest Class Doc Comment
 *
 * @category    Class
 * @description Body parameter class for API method AssetAddOrUpdateSubjectInfo
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AssetAddOrUpdateSubjectInfoBodyWrapperTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AssetAddOrUpdateSubjectInfoBodyWrapper"
     */
    public function testAssetAddOrUpdateSubjectInfoBodyWrapper()
    {
    }

    /**
     * Test attribute "asa_x"
     */
    public function testPropertyAsaX()
    {
    }

    /**
     * Test attribute "asa_y"
     */
    public function testPropertyAsaY()
    {
    }

    /**
     * Test attribute "asa_width"
     */
    public function testPropertyAsaWidth()
    {
    }

    /**
     * Test attribute "asa_height"
     */
    public function testPropertyAsaHeight()
    {
    }

    /**
     * Test attribute "poi_x"
     */
    public function testPropertyPoiX()
    {
    }

    /**
     * Test attribute "poi_y"
     */
    public function testPropertyPoiY()
    {
    }
}
