<?php
/**
 * ResourcesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest API v1.2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ResourcesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResourcesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for restApiAssetAddOrUpdateSubjectInfo
     *
     * AssetAddOrUpdateSubjectInfo.
     *
     */
    public function testRestApiAssetAddOrUpdateSubjectInfo()
    {
    }

    /**
     * Test case for restApiAssetDeleteSubjectInfo
     *
     * AssetDeleteSubjectInfo.
     *
     */
    public function testRestApiAssetDeleteSubjectInfo()
    {
    }

    /**
     * Test case for restApiAssetGetImageInfo
     *
     * AssetGetImageInfo.
     *
     */
    public function testRestApiAssetGetImageInfo()
    {
    }

    /**
     * Test case for restApiAssetGetSubjectInfo
     *
     * AssetGetSubjectInfo.
     *
     */
    public function testRestApiAssetGetSubjectInfo()
    {
    }

    /**
     * Test case for restApiDocumentCopyAnnotations
     *
     * DocumentCopyAnnotations.
     *
     */
    public function testRestApiDocumentCopyAnnotations()
    {
    }

    /**
     * Test case for restApiDocumentCopyDocumentEventActions
     *
     * DocumentCopyDocumentEventActions.
     *
     */
    public function testRestApiDocumentCopyDocumentEventActions()
    {
    }

    /**
     * Test case for restApiDocumentCopyVariableDefinitions
     *
     * DocumentCopyVariableDefinitions.
     *
     */
    public function testRestApiDocumentCopyVariableDefinitions()
    {
    }

    /**
     * Test case for restApiDocumentCreateFromBlankDocTemplate
     *
     * DocumentCreateFromBlankDocTemplate.
     *
     */
    public function testRestApiDocumentCreateFromBlankDocTemplate()
    {
    }

    /**
     * Test case for restApiDocumentCreateFromChiliPackage
     *
     * DocumentCreateFromChiliPackage.
     *
     */
    public function testRestApiDocumentCreateFromChiliPackage()
    {
    }

    /**
     * Test case for restApiDocumentCreateFromODT
     *
     * DocumentCreateFromODT.
     *
     */
    public function testRestApiDocumentCreateFromODT()
    {
    }

    /**
     * Test case for restApiDocumentCreateFromPDF
     *
     * DocumentCreateFromPDF.
     *
     */
    public function testRestApiDocumentCreateFromPDF()
    {
    }

    /**
     * Test case for restApiDocumentCreateHTML
     *
     * DocumentCreateHTML.
     *
     */
    public function testRestApiDocumentCreateHTML()
    {
    }

    /**
     * Test case for restApiDocumentCreateIDML
     *
     * DocumentCreateIDML.
     *
     */
    public function testRestApiDocumentCreateIDML()
    {
    }

    /**
     * Test case for restApiDocumentCreateImages
     *
     * DocumentCreateImages.
     *
     */
    public function testRestApiDocumentCreateImages()
    {
    }

    /**
     * Test case for restApiDocumentCreateImagesAndPDF
     *
     * DocumentCreateImagesAndPDF.
     *
     */
    public function testRestApiDocumentCreateImagesAndPDF()
    {
    }

    /**
     * Test case for restApiDocumentCreateODF
     *
     * DocumentCreateODF.
     *
     */
    public function testRestApiDocumentCreateODF()
    {
    }

    /**
     * Test case for restApiDocumentCreatePDF
     *
     * DocumentCreatePDF.
     *
     */
    public function testRestApiDocumentCreatePDF()
    {
    }

    /**
     * Test case for restApiDocumentCreatePackage
     *
     * DocumentCreatePackage.
     *
     */
    public function testRestApiDocumentCreatePackage()
    {
    }

    /**
     * Test case for restApiDocumentCreateTempFolding
     *
     * DocumentCreateTempFolding.
     *
     */
    public function testRestApiDocumentCreateTempFolding()
    {
    }

    /**
     * Test case for restApiDocumentCreateTempHTML
     *
     * DocumentCreateTempHTML.
     *
     */
    public function testRestApiDocumentCreateTempHTML()
    {
    }

    /**
     * Test case for restApiDocumentCreateTempIDML
     *
     * DocumentCreateTempIDML.
     *
     */
    public function testRestApiDocumentCreateTempIDML()
    {
    }

    /**
     * Test case for restApiDocumentCreateTempImages
     *
     * DocumentCreateTempImages.
     *
     */
    public function testRestApiDocumentCreateTempImages()
    {
    }

    /**
     * Test case for restApiDocumentCreateTempImagesAndPDF
     *
     * DocumentCreateTempImagesAndPDF.
     *
     */
    public function testRestApiDocumentCreateTempImagesAndPDF()
    {
    }

    /**
     * Test case for restApiDocumentCreateTempODF
     *
     * DocumentCreateTempODF.
     *
     */
    public function testRestApiDocumentCreateTempODF()
    {
    }

    /**
     * Test case for restApiDocumentCreateTempPDF
     *
     * DocumentCreateTempPDF.
     *
     */
    public function testRestApiDocumentCreateTempPDF()
    {
    }

    /**
     * Test case for restApiDocumentCreateTempPackage
     *
     * DocumentCreateTempPackage.
     *
     */
    public function testRestApiDocumentCreateTempPackage()
    {
    }

    /**
     * Test case for restApiDocumentGetAnnotations
     *
     * DocumentGetAnnotations.
     *
     */
    public function testRestApiDocumentGetAnnotations()
    {
    }

    /**
     * Test case for restApiDocumentGetDefaultSettings
     *
     * DocumentGetDefaultSettings.
     *
     */
    public function testRestApiDocumentGetDefaultSettings()
    {
    }

    /**
     * Test case for restApiDocumentGetDocumentEventActions
     *
     * DocumentGetDocumentEventActions.
     *
     */
    public function testRestApiDocumentGetDocumentEventActions()
    {
    }

    /**
     * Test case for restApiDocumentGetFoldingViewerURL
     *
     * DocumentGetFoldingViewerURL.
     *
     */
    public function testRestApiDocumentGetFoldingViewerURL()
    {
    }

    /**
     * Test case for restApiDocumentGetHTMLEditorURL
     *
     * DocumentGetHTMLEditorURL.
     *
     */
    public function testRestApiDocumentGetHTMLEditorURL()
    {
    }

    /**
     * Test case for restApiDocumentGetHTMLFoldingViewerURL
     *
     * DocumentGetHTMLFoldingViewerURL.
     *
     */
    public function testRestApiDocumentGetHTMLFoldingViewerURL()
    {
    }

    /**
     * Test case for restApiDocumentGetHTMLPreload
     *
     * DocumentGetHTMLPreload.
     *
     */
    public function testRestApiDocumentGetHTMLPreload()
    {
    }

    /**
     * Test case for restApiDocumentGetHTMLPreloadURL
     *
     * DocumentGetHTMLPreloadURL.
     *
     */
    public function testRestApiDocumentGetHTMLPreloadURL()
    {
    }

    /**
     * Test case for restApiDocumentGetHTMLThreeDModelViewerURL
     *
     * DocumentGetHTMLThreeDModelViewerURL.
     *
     */
    public function testRestApiDocumentGetHTMLThreeDModelViewerURL()
    {
    }

    /**
     * Test case for restApiDocumentGetInfo
     *
     * DocumentGetInfo.
     *
     */
    public function testRestApiDocumentGetInfo()
    {
    }

    /**
     * Test case for restApiDocumentGetPreflightResults
     *
     * DocumentGetPreflightResults.
     *
     */
    public function testRestApiDocumentGetPreflightResults()
    {
    }

    /**
     * Test case for restApiDocumentGetThreeDModelViewerURL
     *
     * DocumentGetThreeDModelViewerURL.
     *
     */
    public function testRestApiDocumentGetThreeDModelViewerURL()
    {
    }

    /**
     * Test case for restApiDocumentGetUsedAssets
     *
     * DocumentGetUsedAssets.
     *
     */
    public function testRestApiDocumentGetUsedAssets()
    {
    }

    /**
     * Test case for restApiDocumentGetVariableDefinitions
     *
     * DocumentGetVariableDefinitions.
     *
     */
    public function testRestApiDocumentGetVariableDefinitions()
    {
    }

    /**
     * Test case for restApiDocumentGetVariableValues
     *
     * DocumentGetVariableValues.
     *
     */
    public function testRestApiDocumentGetVariableValues()
    {
    }

    /**
     * Test case for restApiDocumentProcessServerSide
     *
     * DocumentProcessServerSide.
     *
     */
    public function testRestApiDocumentProcessServerSide()
    {
    }

    /**
     * Test case for restApiDocumentSetAnnotations
     *
     * DocumentSetAnnotations.
     *
     */
    public function testRestApiDocumentSetAnnotations()
    {
    }

    /**
     * Test case for restApiDocumentSetAssetDirectories
     *
     * DocumentSetAssetDirectories.
     *
     */
    public function testRestApiDocumentSetAssetDirectories()
    {
    }

    /**
     * Test case for restApiDocumentSetConstraints
     *
     * DocumentSetConstraints.
     *
     */
    public function testRestApiDocumentSetConstraints()
    {
    }

    /**
     * Test case for restApiDocumentSetDataSource
     *
     * DocumentSetDataSource.
     *
     */
    public function testRestApiDocumentSetDataSource()
    {
    }

    /**
     * Test case for restApiDocumentSetDocumentEventActions
     *
     * DocumentSetDocumentEventActions.
     *
     */
    public function testRestApiDocumentSetDocumentEventActions()
    {
    }

    /**
     * Test case for restApiDocumentSetVariableDefinitions
     *
     * DocumentSetVariableDefinitions.
     *
     */
    public function testRestApiDocumentSetVariableDefinitions()
    {
    }

    /**
     * Test case for restApiDocumentSetVariableValues
     *
     * DocumentSetVariableValues.
     *
     */
    public function testRestApiDocumentSetVariableValues()
    {
    }

    /**
     * Test case for restApiDownloadAssets
     *
     * DownloadAssets.
     *
     */
    public function testRestApiDownloadAssets()
    {
    }

    /**
     * Test case for restApiDownloadDatasourceSample
     *
     * DownloadDatasourceSample.
     *
     */
    public function testRestApiDownloadDatasourceSample()
    {
    }

    /**
     * Test case for restApiDownloadExternal
     *
     * DownloadExternal.
     *
     */
    public function testRestApiDownloadExternal()
    {
    }

    /**
     * Test case for restApiDownloadFolding
     *
     * DownloadFolding.
     *
     */
    public function testRestApiDownloadFolding()
    {
    }

    /**
     * Test case for restApiDownloadFontPreview
     *
     * DownloadFontPreview.
     *
     */
    public function testRestApiDownloadFontPreview()
    {
    }

    /**
     * Test case for restApiDownloadIcons
     *
     * DownloadIcons.
     *
     */
    public function testRestApiDownloadIcons()
    {
    }

    /**
     * Test case for restApiDownloadLoginBackground
     *
     * DownloadLoginBackground.
     *
     */
    public function testRestApiDownloadLoginBackground()
    {
    }

    /**
     * Test case for restApiDownloadReflectionMap
     *
     * DownloadReflectionMap.
     *
     */
    public function testRestApiDownloadReflectionMap()
    {
    }

    /**
     * Test case for restApiDownloadTempFile
     *
     * DownloadTempFile.
     *
     */
    public function testRestApiDownloadTempFile()
    {
    }

    /**
     * Test case for restApiFontGetIncludedGlyphs
     *
     * FontGetIncludedGlyphs.
     *
     */
    public function testRestApiFontGetIncludedGlyphs()
    {
    }

    /**
     * Test case for restApiResourceFolderAdd
     *
     * ResourceFolderAdd.
     *
     */
    public function testRestApiResourceFolderAdd()
    {
    }

    /**
     * Test case for restApiResourceFolderCopy
     *
     * ResourceFolderCopy.
     *
     */
    public function testRestApiResourceFolderCopy()
    {
    }

    /**
     * Test case for restApiResourceFolderDelete
     *
     * ResourceFolderDelete.
     *
     */
    public function testRestApiResourceFolderDelete()
    {
    }

    /**
     * Test case for restApiResourceFolderMove
     *
     * ResourceFolderMove.
     *
     */
    public function testRestApiResourceFolderMove()
    {
    }

    /**
     * Test case for restApiResourceGetHistory
     *
     * ResourceGetHistory.
     *
     */
    public function testRestApiResourceGetHistory()
    {
    }

    /**
     * Test case for restApiResourceGetTree
     *
     * ResourceGetTree.
     *
     */
    public function testRestApiResourceGetTree()
    {
    }

    /**
     * Test case for restApiResourceGetTreeLevel
     *
     * ResourceGetTreeLevel.
     *
     */
    public function testRestApiResourceGetTreeLevel()
    {
    }

    /**
     * Test case for restApiResourceItemAdd
     *
     * ResourceItemAdd.
     *
     */
    public function testRestApiResourceItemAdd()
    {
    }

    /**
     * Test case for restApiResourceItemAddFromURL
     *
     * ResourceItemAddFromURL.
     *
     */
    public function testRestApiResourceItemAddFromURL()
    {
    }

    /**
     * Test case for restApiResourceItemAddFromURLWithModificationDate
     *
     * ResourceItemAddFromURLWithModificationDate.
     *
     */
    public function testRestApiResourceItemAddFromURLWithModificationDate()
    {
    }

    /**
     * Test case for restApiResourceItemAddPreviewOverride
     *
     * ResourceItemAddPreviewOverride.
     *
     */
    public function testRestApiResourceItemAddPreviewOverride()
    {
    }

    /**
     * Test case for restApiResourceItemAddWithPreview
     *
     * ResourceItemAddWithPreview.
     *
     */
    public function testRestApiResourceItemAddWithPreview()
    {
    }

    /**
     * Test case for restApiResourceItemCopy
     *
     * ResourceItemCopy.
     *
     */
    public function testRestApiResourceItemCopy()
    {
    }

    /**
     * Test case for restApiResourceItemDelete
     *
     * ResourceItemDelete.
     *
     */
    public function testRestApiResourceItemDelete()
    {
    }

    /**
     * Test case for restApiResourceItemGetByIdOrPath
     *
     * ResourceItemGetByIdOrPath.
     *
     */
    public function testRestApiResourceItemGetByIdOrPath()
    {
    }

    /**
     * Test case for restApiResourceItemGetByName
     *
     * ResourceItemGetByName.
     *
     */
    public function testRestApiResourceItemGetByName()
    {
    }

    /**
     * Test case for restApiResourceItemGetByPath
     *
     * ResourceItemGetByPath.
     *
     */
    public function testRestApiResourceItemGetByPath()
    {
    }

    /**
     * Test case for restApiResourceItemGetCacheInfo
     *
     * ResourceItemGetCacheInfo.
     *
     */
    public function testRestApiResourceItemGetCacheInfo()
    {
    }

    /**
     * Test case for restApiResourceItemGetCustomMetaData
     *
     * ResourceItemGetCustomMetaData.
     *
     */
    public function testRestApiResourceItemGetCustomMetaData()
    {
    }

    /**
     * Test case for restApiResourceItemGetDefinitionXML
     *
     * ResourceItemGetDefinitionXML.
     *
     */
    public function testRestApiResourceItemGetDefinitionXML()
    {
    }

    /**
     * Test case for restApiResourceItemGetHistory
     *
     * ResourceItemGetHistory.
     *
     */
    public function testRestApiResourceItemGetHistory()
    {
    }

    /**
     * Test case for restApiResourceItemGetPrivateInfo
     *
     * ResourceItemGetPrivateInfo.
     *
     */
    public function testRestApiResourceItemGetPrivateInfo()
    {
    }

    /**
     * Test case for restApiResourceItemGetTransformedURL
     *
     * ResourceItemGetTransformedURL.
     *
     */
    public function testRestApiResourceItemGetTransformedURL()
    {
    }

    /**
     * Test case for restApiResourceItemGetTransformedURLWithDebugInfo
     *
     * ResourceItemGetTransformedURLWithDebugInfo.
     *
     */
    public function testRestApiResourceItemGetTransformedURLWithDebugInfo()
    {
    }

    /**
     * Test case for restApiResourceItemGetURL
     *
     * ResourceItemGetURL.
     *
     */
    public function testRestApiResourceItemGetURL()
    {
    }

    /**
     * Test case for restApiResourceItemGetURLForAnonymousUser
     *
     * ResourceItemGetURLForAnonymousUser.
     *
     */
    public function testRestApiResourceItemGetURLForAnonymousUser()
    {
    }

    /**
     * Test case for restApiResourceItemGetURLWithDebugInfo
     *
     * ResourceItemGetURLWithDebugInfo.
     *
     */
    public function testRestApiResourceItemGetURLWithDebugInfo()
    {
    }

    /**
     * Test case for restApiResourceItemGetXML
     *
     * ResourceItemGetXML.
     *
     */
    public function testRestApiResourceItemGetXML()
    {
    }

    /**
     * Test case for restApiResourceItemMove
     *
     * ResourceItemMove.
     *
     */
    public function testRestApiResourceItemMove()
    {
    }

    /**
     * Test case for restApiResourceItemRemovePreviewOverride
     *
     * ResourceItemRemovePreviewOverride.
     *
     */
    public function testRestApiResourceItemRemovePreviewOverride()
    {
    }

    /**
     * Test case for restApiResourceItemReplaceFile
     *
     * ResourceItemReplaceFile.
     *
     */
    public function testRestApiResourceItemReplaceFile()
    {
    }

    /**
     * Test case for restApiResourceItemReplaceFileWithPreviewOverride
     *
     * ResourceItemReplaceFileWithPreviewOverride.
     *
     */
    public function testRestApiResourceItemReplaceFileWithPreviewOverride()
    {
    }

    /**
     * Test case for restApiResourceItemResetPreviews
     *
     * ResourceItemResetPreviews.
     *
     */
    public function testRestApiResourceItemResetPreviews()
    {
    }

    /**
     * Test case for restApiResourceItemSave
     *
     * ResourceItemSave.
     *
     */
    public function testRestApiResourceItemSave()
    {
    }

    /**
     * Test case for restApiResourceItemSaveCustomMetaData
     *
     * ResourceItemSaveCustomMetaData.
     *
     */
    public function testRestApiResourceItemSaveCustomMetaData()
    {
    }

    /**
     * Test case for restApiResourceItemsAddFromZip
     *
     * ResourceItemsAddFromZip.
     *
     */
    public function testRestApiResourceItemsAddFromZip()
    {
    }

    /**
     * Test case for restApiResourceLibraryGetSettings
     *
     * ResourceLibraryGetSettings.
     *
     */
    public function testRestApiResourceLibraryGetSettings()
    {
    }

    /**
     * Test case for restApiResourceLibrarySaveSettings
     *
     * ResourceLibrarySaveSettings.
     *
     */
    public function testRestApiResourceLibrarySaveSettings()
    {
    }

    /**
     * Test case for restApiResourceList
     *
     * ResourceList.
     *
     */
    public function testRestApiResourceList()
    {
    }

    /**
     * Test case for restApiResourceSearch
     *
     * ResourceSearch.
     *
     */
    public function testRestApiResourceSearch()
    {
    }

    /**
     * Test case for restApiResourceSearchByIDs
     *
     * ResourceSearchByIDs.
     *
     */
    public function testRestApiResourceSearchByIDs()
    {
    }

    /**
     * Test case for restApiResourceSearchInFolder
     *
     * ResourceSearchInFolder.
     *
     */
    public function testRestApiResourceSearchInFolder()
    {
    }

    /**
     * Test case for restApiResourceSearchPaged
     *
     * ResourceSearchPaged.
     *
     */
    public function testRestApiResourceSearchPaged()
    {
    }

    /**
     * Test case for restApiResourceSearchPagedWithSorting
     *
     * ResourceSearchPagedWithSorting.
     *
     */
    public function testRestApiResourceSearchPagedWithSorting()
    {
    }

    /**
     * Test case for restApiSetNextResourceItemID
     *
     * SetNextResourceItemID.
     *
     */
    public function testRestApiSetNextResourceItemID()
    {
    }

    /**
     * Test case for restApiThreeDModelCreatePackage
     *
     * ThreeDModelCreatePackage.
     *
     */
    public function testRestApiThreeDModelCreatePackage()
    {
    }

    /**
     * Test case for restApiUploadExternalAsset
     *
     * UploadExternalAsset.
     *
     */
    public function testRestApiUploadExternalAsset()
    {
    }
}
