<?php
/**
 * SettingsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest API v1.2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SettingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SettingsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for restApiDataSourceAddSampleFile
     *
     * DataSourceAddSampleFile.
     *
     */
    public function testRestApiDataSourceAddSampleFile()
    {
    }

    /**
     * Test case for restApiDataSourceDeleteSampleFile
     *
     * DataSourceDeleteSampleFile.
     *
     */
    public function testRestApiDataSourceDeleteSampleFile()
    {
    }

    /**
     * Test case for restApiDataSourceDownloadSpreadsheets
     *
     * DataSourceDownloadSpreadsheets.
     *
     */
    public function testRestApiDataSourceDownloadSpreadsheets()
    {
    }

    /**
     * Test case for restApiDataSourceDownloadURL
     *
     * DataSourceDownloadURL.
     *
     */
    public function testRestApiDataSourceDownloadURL()
    {
    }

    /**
     * Test case for restApiDataSourceFileGetXML
     *
     * DataSourceFileGetXML.
     *
     */
    public function testRestApiDataSourceFileGetXML()
    {
    }

    /**
     * Test case for restApiDataSourceListSampleFiles
     *
     * DataSourceListSampleFiles.
     *
     */
    public function testRestApiDataSourceListSampleFiles()
    {
    }

    /**
     * Test case for restApiDataSourceSalesForceGetXML
     *
     * DataSourceSalesForceGetXML.
     *
     */
    public function testRestApiDataSourceSalesForceGetXML()
    {
    }

    /**
     * Test case for restApiDataSourceSpreadsheetGetXML
     *
     * DataSourceSpreadsheetGetXML.
     *
     */
    public function testRestApiDataSourceSpreadsheetGetXML()
    {
    }

    /**
     * Test case for restApiDynamicAssetProviderGetTempAsset
     *
     * DynamicAssetProviderGetTempAsset.
     *
     */
    public function testRestApiDynamicAssetProviderGetTempAsset()
    {
    }

    /**
     * Test case for restApiFoldingSettingCreatePackage
     *
     * FoldingSettingCreatePackage.
     *
     */
    public function testRestApiFoldingSettingCreatePackage()
    {
    }

    /**
     * Test case for restApiODTGetStyles
     *
     * ODTGetStyles.
     *
     */
    public function testRestApiODTGetStyles()
    {
    }

    /**
     * Test case for restApiODTGetTextFlow
     *
     * ODTGetTextFlow.
     *
     */
    public function testRestApiODTGetTextFlow()
    {
    }

    /**
     * Test case for restApiSwitchServerFlowGetCheckPoints
     *
     * SwitchServerFlowGetCheckPoints.
     *
     */
    public function testRestApiSwitchServerFlowGetCheckPoints()
    {
    }

    /**
     * Test case for restApiSwitchServerFlowGetElementsJobCount
     *
     * SwitchServerFlowGetElementsJobCount.
     *
     */
    public function testRestApiSwitchServerFlowGetElementsJobCount()
    {
    }

    /**
     * Test case for restApiSwitchServerFlowGetFullConfig
     *
     * SwitchServerFlowGetFullConfig.
     *
     */
    public function testRestApiSwitchServerFlowGetFullConfig()
    {
    }

    /**
     * Test case for restApiSwitchServerFlowGetJobs
     *
     * SwitchServerFlowGetJobs.
     *
     */
    public function testRestApiSwitchServerFlowGetJobs()
    {
    }

    /**
     * Test case for restApiSwitchServerFlowGetSubmitPoints
     *
     * SwitchServerFlowGetSubmitPoints.
     *
     */
    public function testRestApiSwitchServerFlowGetSubmitPoints()
    {
    }

    /**
     * Test case for restApiSwitchServerFlowSubmitFileToFolder
     *
     * SwitchServerFlowSubmitFileToFolder.
     *
     */
    public function testRestApiSwitchServerFlowSubmitFileToFolder()
    {
    }

    /**
     * Test case for restApiSwitchServerFlowSubmitFileToSubmitPoint
     *
     * SwitchServerFlowSubmitFileToSubmitPoint.
     *
     */
    public function testRestApiSwitchServerFlowSubmitFileToSubmitPoint()
    {
    }

    /**
     * Test case for restApiSwitchServerGetFlowList
     *
     * SwitchServerGetFlowList.
     *
     */
    public function testRestApiSwitchServerGetFlowList()
    {
    }

    /**
     * Test case for restApiSwitchServerTestConnection
     *
     * SwitchServerTestConnection.
     *
     */
    public function testRestApiSwitchServerTestConnection()
    {
    }

    /**
     * Test case for restApiXinetExecutePortalDICall
     *
     * XinetExecutePortalDICall.
     *
     */
    public function testRestApiXinetExecutePortalDICall()
    {
    }

    /**
     * Test case for restApiXinetSetCurrentCredentials
     *
     * XinetSetCurrentCredentials.
     *
     */
    public function testRestApiXinetSetCurrentCredentials()
    {
    }

    /**
     * Test case for restApiXinetTestConnection
     *
     * XinetTestConnection.
     *
     */
    public function testRestApiXinetTestConnection()
    {
    }
}
