<?php
/**
 * SystemApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest API v1.2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SystemApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SystemApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for restApiApiKeyClearHeaderFieldsForServerDownloads
     *
     * ApiKeyClearHeaderFieldsForServerDownloads.
     *
     */
    public function testRestApiApiKeyClearHeaderFieldsForServerDownloads()
    {
    }

    /**
     * Test case for restApiApiKeyGetCurrentSettings
     *
     * ApiKeyGetCurrentSettings.
     *
     */
    public function testRestApiApiKeyGetCurrentSettings()
    {
    }

    /**
     * Test case for restApiApiKeyKeepAlive
     *
     * ApiKeyKeepAlive.
     *
     */
    public function testRestApiApiKeyKeepAlive()
    {
    }

    /**
     * Test case for restApiApiKeySetHeaderFieldForServerDownloads
     *
     * ApiKeySetHeaderFieldForServerDownloads.
     *
     */
    public function testRestApiApiKeySetHeaderFieldForServerDownloads()
    {
    }

    /**
     * Test case for restApiApiKeySetRequestHeaderForDomain
     *
     * ApiKeySetRequestHeaderForDomain.
     *
     */
    public function testRestApiApiKeySetRequestHeaderForDomain()
    {
    }

    /**
     * Test case for restApiApiKeySetRequestWithCredentialsForDomain
     *
     * ApiKeySetRequestWithCredentialsForDomain.
     *
     */
    public function testRestApiApiKeySetRequestWithCredentialsForDomain()
    {
    }

    /**
     * Test case for restApiApiKeyVerify
     *
     * ApiKeyVerify.
     *
     */
    public function testRestApiApiKeyVerify()
    {
    }

    /**
     * Test case for restApiCsvFileCreate
     *
     * CsvFileCreate.
     *
     */
    public function testRestApiCsvFileCreate()
    {
    }

    /**
     * Test case for restApiDownloadURL
     *
     * DownloadURL.
     *
     */
    public function testRestApiDownloadURL()
    {
    }

    /**
     * Test case for restApiEnvironmentAdd
     *
     * EnvironmentAdd.
     *
     */
    public function testRestApiEnvironmentAdd()
    {
    }

    /**
     * Test case for restApiEnvironmentCopy
     *
     * EnvironmentCopy.
     *
     */
    public function testRestApiEnvironmentCopy()
    {
    }

    /**
     * Test case for restApiEnvironmentDelete
     *
     * EnvironmentDelete.
     *
     */
    public function testRestApiEnvironmentDelete()
    {
    }

    /**
     * Test case for restApiEnvironmentGetColorProfiles
     *
     * EnvironmentGetColorProfiles.
     *
     */
    public function testRestApiEnvironmentGetColorProfiles()
    {
    }

    /**
     * Test case for restApiEnvironmentGetCurrent
     *
     * EnvironmentGetCurrent.
     *
     */
    public function testRestApiEnvironmentGetCurrent()
    {
    }

    /**
     * Test case for restApiEnvironmentGetLoginSettings
     *
     * EnvironmentGetLoginSettings.
     *
     */
    public function testRestApiEnvironmentGetLoginSettings()
    {
    }

    /**
     * Test case for restApiEnvironmentGetReflectionMaps
     *
     * EnvironmentGetReflectionMaps.
     *
     */
    public function testRestApiEnvironmentGetReflectionMaps()
    {
    }

    /**
     * Test case for restApiEnvironmentGetSettings
     *
     * EnvironmentGetSettings.
     *
     */
    public function testRestApiEnvironmentGetSettings()
    {
    }

    /**
     * Test case for restApiEnvironmentList
     *
     * EnvironmentList.
     *
     */
    public function testRestApiEnvironmentList()
    {
    }

    /**
     * Test case for restApiEnvironmentSaveSettings
     *
     * EnvironmentSaveSettings.
     *
     */
    public function testRestApiEnvironmentSaveSettings()
    {
    }

    /**
     * Test case for restApiGenerateApiKey
     *
     * GenerateApiKey.
     *
     */
    public function testRestApiGenerateApiKey()
    {
    }

    /**
     * Test case for restApiGenerateApiKeyWithSettings
     *
     * GenerateApiKeyWithSettings.
     *
     */
    public function testRestApiGenerateApiKeyWithSettings()
    {
    }

    /**
     * Test case for restApiGetFontURL
     *
     * GetFontURL.
     *
     */
    public function testRestApiGetFontURL()
    {
    }

    /**
     * Test case for restApiGetServerDate
     *
     * GetServerDate.
     *
     */
    public function testRestApiGetServerDate()
    {
    }

    /**
     * Test case for restApiGoogleCreateAuthorizationUrl
     *
     * GoogleCreateAuthorizationUrl.
     *
     */
    public function testRestApiGoogleCreateAuthorizationUrl()
    {
    }

    /**
     * Test case for restApiInterfaceGetInitialSettings
     *
     * InterfaceGetInitialSettings.
     *
     */
    public function testRestApiInterfaceGetInitialSettings()
    {
    }

    /**
     * Test case for restApiLanguageGetCombinedStrings
     *
     * LanguageGetCombinedStrings.
     *
     */
    public function testRestApiLanguageGetCombinedStrings()
    {
    }

    /**
     * Test case for restApiLanguageGetCsvURL
     *
     * LanguageGetCsvURL.
     *
     */
    public function testRestApiLanguageGetCsvURL()
    {
    }

    /**
     * Test case for restApiLanguageGetUnicodeTextURL
     *
     * LanguageGetUnicodeTextURL.
     *
     */
    public function testRestApiLanguageGetUnicodeTextURL()
    {
    }

    /**
     * Test case for restApiLanguageImportCsv
     *
     * LanguageImportCsv.
     *
     */
    public function testRestApiLanguageImportCsv()
    {
    }

    /**
     * Test case for restApiLanguageImportUnicodeText
     *
     * LanguageImportUnicodeText.
     *
     */
    public function testRestApiLanguageImportUnicodeText()
    {
    }

    /**
     * Test case for restApiLanguageSaveStrings
     *
     * LanguageSaveStrings.
     *
     */
    public function testRestApiLanguageSaveStrings()
    {
    }

    /**
     * Test case for restApiLanguagesGetList
     *
     * LanguagesGetList.
     *
     */
    public function testRestApiLanguagesGetList()
    {
    }

    /**
     * Test case for restApiLockApiKey
     *
     * LockApiKey.
     *
     */
    public function testRestApiLockApiKey()
    {
    }

    /**
     * Test case for restApiServerGetLicenseInfo
     *
     * ServerGetLicenseInfo.
     *
     */
    public function testRestApiServerGetLicenseInfo()
    {
    }

    /**
     * Test case for restApiServerGetLoggingSettings
     *
     * ServerGetLoggingSettings.
     *
     */
    public function testRestApiServerGetLoggingSettings()
    {
    }

    /**
     * Test case for restApiServerGetSettings
     *
     * ServerGetSettings.
     *
     */
    public function testRestApiServerGetSettings()
    {
    }

    /**
     * Test case for restApiServerLicenseRequest
     *
     * ServerLicenseRequest.
     *
     */
    public function testRestApiServerLicenseRequest()
    {
    }

    /**
     * Test case for restApiServerLogClear
     *
     * ServerLogClear.
     *
     */
    public function testRestApiServerLogClear()
    {
    }

    /**
     * Test case for restApiServerSaveLoggingSettings
     *
     * ServerSaveLoggingSettings.
     *
     */
    public function testRestApiServerSaveLoggingSettings()
    {
    }

    /**
     * Test case for restApiServerSaveSettings
     *
     * ServerSaveSettings.
     *
     */
    public function testRestApiServerSaveSettings()
    {
    }

    /**
     * Test case for restApiSetAssetDirectories
     *
     * SetAssetDirectories.
     *
     */
    public function testRestApiSetAssetDirectories()
    {
    }

    /**
     * Test case for restApiSetAutomaticPreviewGeneration
     *
     * SetAutomaticPreviewGeneration.
     *
     */
    public function testRestApiSetAutomaticPreviewGeneration()
    {
    }

    /**
     * Test case for restApiSetContentAdministration
     *
     * SetContentAdministration.
     *
     */
    public function testRestApiSetContentAdministration()
    {
    }

    /**
     * Test case for restApiSetUserLanguage
     *
     * SetUserLanguage.
     *
     */
    public function testRestApiSetUserLanguage()
    {
    }

    /**
     * Test case for restApiSetWorkingEnvironment
     *
     * SetWorkingEnvironment.
     *
     */
    public function testRestApiSetWorkingEnvironment()
    {
    }

    /**
     * Test case for restApiSetWorkspaceAdministration
     *
     * SetWorkspaceAdministration.
     *
     */
    public function testRestApiSetWorkspaceAdministration()
    {
    }

    /**
     * Test case for restApiTaskGetEditorCliLog
     *
     * TaskGetEditorCliLog.
     *
     */
    public function testRestApiTaskGetEditorCliLog()
    {
    }

    /**
     * Test case for restApiTaskGetStatus
     *
     * TaskGetStatus.
     *
     */
    public function testRestApiTaskGetStatus()
    {
    }

    /**
     * Test case for restApiTaskGetStatusAndRemoveIfCompleted
     *
     * TaskGetStatusAndRemoveIfCompleted.
     *
     */
    public function testRestApiTaskGetStatusAndRemoveIfCompleted()
    {
    }

    /**
     * Test case for restApiTaskRemoveFromLog
     *
     * TaskRemoveFromLog.
     *
     */
    public function testRestApiTaskRemoveFromLog()
    {
    }

    /**
     * Test case for restApiTasksGetList
     *
     * TasksGetList.
     *
     */
    public function testRestApiTasksGetList()
    {
    }

    /**
     * Test case for restApiTasksGetQueueOverview
     *
     * TasksGetQueueOverview.
     *
     */
    public function testRestApiTasksGetQueueOverview()
    {
    }

    /**
     * Test case for restApiTasksGetStatusses
     *
     * TasksGetStatusses.
     *
     */
    public function testRestApiTasksGetStatusses()
    {
    }
}
